# This is a basic workflow to help you get started with Actions

name: BE-Common

# Controls when the action will run. 
on:
  push:
    branches: [master]

  pull_request:
      branches:
        - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trigger_common_util:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch from Github
      uses: actions/checkout@v2
    - env:
        ci_token: ${{ secrets.CI_TOKEN }}
    - run: |
       curl \
       -X POST \
       -H "Accept: application/vnd.github.v3+json" \
       -H "Authorization: bearer $env:ci_token" \
       https://api.github.com/repos/notabarista/be-common-util/actions/workflows/be_common_util.yml/dispatches \
       -d '{"ref":"pipeline_common_config"}' \

  be_common_java__11_x64:
    needs:   trigger_common_util
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout branch from Github 
        uses: actions/checkout@v2
        
      - name: Setup JDK 11.0.10
        uses: actions/setup-java@v1
        with:
         java-version: '11.0.10'
         architecture: x64
         
      - name: Build with maven
        run: mvn dependency:tree clean install
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
